# Generated by Django 5.1.6 on 2025-03-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otras_fuentes', '0005_metodooperacion_tipodesecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='nombrefuentecontaminante',
            name='coordenada_e',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nombrefuentecontaminante',
            name='coordenada_n',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
