# Generated by Django 5.1.6 on 2025-03-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otras_fuentes', '0006_nombrefuentecontaminante_coordenada_e_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoResidual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
    ]
