# Generated by Django 5.1.6 on 2025-03-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otras_fuentes', '0008_categoria_cuerporeceptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
    ]
