# Generated by Django 5.1.6 on 2025-03-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otras_fuentes', '0009_sistematratamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nombrefuentecontaminante',
            name='coordenada_e',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nombrefuentecontaminante',
            name='coordenada_n',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
