# Generated by Django 5.1.6 on 2025-03-05 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otras_fuentes', '0010_alter_nombrefuentecontaminante_coordenada_e_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nombrefuentecontaminante',
            name='municipio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.municipio'),
        ),
    ]
