# Generated by Django 5.1.6 on 2025-03-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otras_fuentes', '0014_nombrefuentecontaminante_oace'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreVertedero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('anio_inaugurado', models.IntegerField()),
                ('cuenca_hidrografica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.cuencahidrografica')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.municipio')),
            ],
        ),
    ]
