# Generated by Django 5.1.6 on 2025-04-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otras_fuentes', '0017_entidaddp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nombrefuentecontaminante',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.municipio'),
        ),
        migrations.AlterField(
            model_name='nombrefuentecontaminante',
            name='oace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.oace'),
        ),
    ]
