# Generated by Django 5.1.6 on 2025-02-19 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otras_fuentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('residuales_liquidos_caracterizados', models.BooleanField(default=False)),
                ('cumple_norma_vertimiento', models.BooleanField(default=False)),
                ('permiso_vertimiento_vigente', models.BooleanField(default=False)),
                ('priorizado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(default=2025)),
                ('cuenca_hidrografica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.cuencahidrografica')),
                ('cuerpo_agua_afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.cuerpoaguaafectado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.municipio')),
                ('nombre_fc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.nombrefuentecontaminante')),
                ('oace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.oace')),
                ('organos_gobierno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.organos_gobierno')),
                ('osde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.osde')),
                ('otras_instituciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.otras_instituciones')),
                ('prioridad_fc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.prioridad_fc')),
                ('uso_principal_afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.usoprincipalafectado')),
            ],
        ),
    ]
