# Generated by Django 5.1.6 on 2025-02-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidos',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
