# Generated by Django 5.1.6 on 2025-02-22 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0002_alter_liquidos_no'),
        ('otras_fuentes', '0002_subordinacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True)),
                ('codigo_nae', models.IntegerField(blank=True, null=True)),
                ('carga_generada', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('carga_dispuesta', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('reduccion_carga', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('emision_carga', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('acciones_cumplir_nc', models.IntegerField(blank=True, null=True)),
                ('acciones_cumplidas', models.IntegerField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('cumple_norma_vertimiento', models.BooleanField(default=False)),
                ('causa_incumplimiento', models.TextField(blank=True, null=True)),
                ('priorizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(default=2025)),
                ('cuenca_hidrografica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.cuencahidrografica')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.nombrefuentecontaminante')),
                ('oace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.oace')),
                ('subordinacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.subordinacion')),
            ],
        ),
    ]
