# Generated by Django 5.1.6 on 2025-02-27 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0004_alter_fcft_subordinacion'),
        ('otras_fuentes', '0003_codigonae_tipocombustible_contenidoazufre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atmosferas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flujo_gas_emitido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('altura_chimeneas', models.CharField(max_length=255)),
                ('diametro_interno_chimenea', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diametro_externo_chimenea', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_gases', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dispositivo_control_emisiones', models.TextField(blank=True, null=True)),
                ('eficiencia_dispositivo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emision_incidental', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion_suceso', models.TextField(blank=True, null=True)),
                ('cumplen_norma_emision', models.BooleanField(default=False)),
                ('acciones_planificadas', models.IntegerField(blank=True, null=True)),
                ('acciones_cumplidas', models.IntegerField(blank=True, null=True)),
                ('monto_financiero', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('causas_incumplimientos', models.TextField(blank=True, null=True)),
                ('priorizado', models.BooleanField(default=False)),
                ('year', models.IntegerField(default=2025)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_nae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.codigonae')),
                ('consumo_combustible', models.ManyToManyField(blank=True, to='otras_fuentes.consumocombustible')),
                ('contenido_azufre', models.ManyToManyField(blank=True, to='otras_fuentes.contenidoazufre')),
                ('cuenca_hidrografica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.cuencahidrografica')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.nombrefuentecontaminante')),
                ('nombre_oace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.oace')),
                ('subordinacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.subordinacion')),
                ('tipo_combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.tipocombustible')),
            ],
        ),
    ]
