# Generated by Django 5.1.6 on 2025-02-27 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0005_atmosferas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosAtmosfera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so2_emitido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('so2_despues_tratamiento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nox_emitido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nox_despues_tratamiento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pm_emitido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pm_despues_tratamiento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pm10_emitido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pm10_despues_tratamiento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nh3_emitido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nh3_despues_tratamiento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('atmosfera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='Contaminantes.atmosferas')),
            ],
        ),
    ]
