# Generated by Django 5.1.6 on 2025-02-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0007_alter_parametrosatmosfera_nh3_despues_tratamiento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParametrosAtmosfera',
        ),
    ]
