# Generated by Django 5.1.6 on 2025-02-28 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0008_delete_parametrosatmosfera'),
        ('otras_fuentes', '0004_desechogenerado_practica'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesechosPeligroso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_practica_1_r', models.IntegerField()),
                ('cantidad_practica_2_r', models.IntegerField()),
                ('cantidad_practica_3_r', models.IntegerField()),
                ('cantidad_practica_4_r', models.IntegerField()),
                ('cumplidas', models.IntegerField()),
                ('no_cumplidas', models.IntegerField()),
                ('priorizado', models.BooleanField(default=False)),
                ('year', models.IntegerField(default=2025)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuenca_hidrografica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.cuencahidrografica')),
                ('desecho_generado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.desechogenerado')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.nombrefuentecontaminante')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.municipio')),
                ('oace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.oace')),
                ('practica_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practica_1', to='otras_fuentes.practica')),
                ('practica_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practica_2', to='otras_fuentes.practica')),
                ('practica_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practica_3', to='otras_fuentes.practica')),
                ('practica_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practica_4', to='otras_fuentes.practica')),
                ('subordinacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.subordinacion')),
            ],
        ),
    ]
