# Generated by Django 5.1.6 on 2025-02-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0009_desechospeligroso'),
        ('otras_fuentes', '0004_desechogenerado_practica'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atmosferas',
            new_name='Atmosfera',
        ),
        migrations.RenameModel(
            old_name='Liquidos',
            new_name='Liquido',
        ),
    ]
