# Generated by Django 5.1.6 on 2025-02-28 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0010_rename_atmosferas_atmosfera_rename_liquidos_liquido'),
        ('otras_fuentes', '0004_desechogenerado_practica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desechospeligroso',
            name='cantidad_practica_1_r',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='cantidad_practica_2_r',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='cantidad_practica_3_r',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='cantidad_practica_4_r',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='cuenca_hidrografica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.cuencahidrografica'),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='cumplidas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='no_cumplidas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='oace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.oace'),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='practica_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practica_1', to='otras_fuentes.practica'),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='practica_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practica_2', to='otras_fuentes.practica'),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='practica_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practica_3', to='otras_fuentes.practica'),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='practica_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practica_4', to='otras_fuentes.practica'),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='subordinacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.subordinacion'),
        ),
    ]
