# Generated by Django 5.1.6 on 2025-03-03 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0011_alter_desechospeligroso_cantidad_practica_1_r_and_more'),
        ('otras_fuentes', '0005_metodooperacion_tipodesecho'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_inauguracion', models.IntegerField(blank=True, null=True)),
                ('tiempo_vida_util', models.IntegerField(blank=True, null=True)),
                ('tiempo_explotacion', models.IntegerField(blank=True, null=True)),
                ('poblacion_servida', models.IntegerField(blank=True, null=True)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distancia_poblacion_cercana', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('residuos_solidos_depositados', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('construccion_tratamiento_lixiviados', models.BooleanField(default=False)),
                ('instalaciones_control_gases', models.BooleanField(default=False)),
                ('area_delimitada', models.BooleanField(default=False)),
                ('cerca_perimetral', models.BooleanField(default=False)),
                ('control_acceso_vehiculos_personal', models.BooleanField(default=False)),
                ('acciones_recuperacion_personal', models.BooleanField(default=False)),
                ('presencia_ganado', models.BooleanField(default=False)),
                ('celdas_enterramiento_residuos', models.BooleanField(default=False)),
                ('area_residuos_desastres', models.BooleanField(default=False)),
                ('celdas_enterramiento_residuos_peligrosos', models.BooleanField(default=False)),
                ('plan_cierre', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuenca_hidrografica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.cuencahidrografica')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.nombrefuentecontaminante')),
                ('metodo_operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.metodooperacion')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.municipio')),
                ('tipo_desecho', models.ManyToManyField(to='otras_fuentes.tipodesecho')),
            ],
        ),
    ]
