# Generated by Django 5.1.6 on 2025-03-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0012_rsu'),
        ('otras_fuentes', '0006_nombrefuentecontaminante_coordenada_e_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquido',
            name='aguas_externas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liquido',
            name='aguas_internas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liquido',
            name='estado_foco',
            field=models.CharField(choices=[('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal'), ('N', 'No tiene')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='liquido',
            name='tipo_desecho',
            field=models.ManyToManyField(to='otras_fuentes.tipodesecho'),
        ),
    ]
