# Generated by Django 5.1.6 on 2025-03-03 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0013_liquido_aguas_externas_liquido_aguas_internas_and_more'),
        ('otras_fuentes', '0007_tiporesidual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquido',
            name='tipo_desecho',
        ),
        migrations.AddField(
            model_name='liquido',
            name='tipo_residual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.tiporesidual'),
        ),
    ]
