# Generated by Django 5.1.6 on 2025-03-05 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0014_remove_liquido_tipo_desecho_liquido_tipo_residual'),
        ('otras_fuentes', '0008_categoria_cuerporeceptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquido',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.categoria'),
        ),
        migrations.AddField(
            model_name='liquido',
            name='cuerpo_receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.cuerporeceptor'),
        ),
    ]
