# Generated by Django 5.1.6 on 2025-03-05 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0015_liquido_categoria_liquido_cuerpo_receptor'),
        ('otras_fuentes', '0009_sistematratamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquido',
            name='sistema_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.sistematratamiento'),
        ),
    ]
