# Generated by Django 5.1.6 on 2025-03-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0016_liquido_sistema_tratamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquido',
            name='municipio',
        ),
    ]
