# Generated by Django 5.1.6 on 2025-03-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0017_remove_liquido_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquido',
            name='oace',
        ),
    ]
