# Generated by Django 5.1.6 on 2025-03-05 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0019_remove_desechospeligroso_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desechospeligroso',
            name='oace',
        ),
    ]
