# Generated by Django 5.1.6 on 2025-03-05 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0020_remove_desechospeligroso_oace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmosfera',
            name='nombre_oace',
        ),
    ]
