# Generated by Django 5.1.6 on 2025-03-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0021_remove_atmosfera_nombre_oace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcft',
            name='oace',
        ),
    ]
