# Generated by Django 5.1.6 on 2025-03-21 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0023_alter_desechospeligroso_cantidad_practica_1_r_and_more'),
        ('otras_fuentes', '0014_nombrefuentecontaminante_oace'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreVertedero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('anio_inaugurado', models.IntegerField()),
                ('cuenca_hidrografica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.cuencahidrografica')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Vertedero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_vida_util', models.IntegerField()),
                ('tiempo_explotacion', models.IntegerField()),
                ('poblacion_atendida', models.IntegerField()),
                ('area', models.FloatField()),
                ('acciones_planificadas', models.IntegerField()),
                ('distancia_asentamiento_cercano', models.FloatField()),
                ('metodo_operacion', models.CharField(max_length=255)),
                ('total_solidos_depositados', models.FloatField()),
                ('domesticos', models.BooleanField(default=False)),
                ('industriales', models.BooleanField(default=False)),
                ('construccion', models.BooleanField(default=False)),
                ('poda', models.BooleanField(default=False)),
                ('comerciales', models.BooleanField(default=False)),
                ('agropecuarios', models.BooleanField(default=False)),
                ('hospitalarios_no_peligrosos', models.BooleanField(default=False)),
                ('hospitalarios_peligrosos', models.BooleanField(default=False)),
                ('construccion_lixiviados', models.BooleanField(default=False)),
                ('control_gases_operando', models.BooleanField(default=False)),
                ('area_delimitada_cercada', models.BooleanField(default=False)),
                ('control_acceso', models.BooleanField(default=False)),
                ('malos_olores', models.BooleanField(default=False)),
                ('personal_recuperacion', models.BooleanField(default=False)),
                ('presencia_ganado', models.BooleanField(default=False)),
                ('celdas_enterramiento_desechos', models.BooleanField(default=False)),
                ('material_tapado', models.BooleanField(default=False)),
                ('area_desechos_desastre', models.BooleanField(default=False)),
                ('celdas_enterramiento_hospitalarios', models.BooleanField(default=False)),
                ('programa_monitoreo', models.BooleanField(default=False)),
                ('planes_clausura', models.BooleanField(default=False)),
                ('year', models.IntegerField(default=2025)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vertedero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertedero', to='Contaminantes.nombrevertedero')),
            ],
        ),
    ]
