# Generated by Django 5.1.6 on 2025-03-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0024_nombrevertedero_vertedero'),
        ('otras_fuentes', '0015_nombrevertedero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertedero',
            name='vertedero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertedero', to='otras_fuentes.nombrevertedero'),
        ),
        migrations.DeleteModel(
            name='NombreVertedero',
        ),
    ]
