# Generated by Django 5.1.6 on 2025-03-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0025_alter_vertedero_vertedero_delete_nombrevertedero'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquido',
            name='es_real',
            field=models.BooleanField(default=False),
        ),
    ]
