# Generated by Django 5.1.6 on 2025-03-29 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0026_liquido_es_real'),
        ('otras_fuentes', '0015_nombrevertedero'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolvosParticula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('prioridad', models.IntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')])),
                ('organismo', models.CharField(max_length=50)),
                ('emisiones_no2', models.FloatField()),
                ('emisiones_so2', models.FloatField()),
                ('emisiones_pm10', models.FloatField()),
                ('emisiones_pm25', models.FloatField()),
                ('emisiones_co', models.FloatField()),
                ('emisiones_covdm', models.FloatField()),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.municipio')),
            ],
            options={
                'indexes': [models.Index(fields=['prioridad'], name='prioridad_idx')],
            },
        ),
    ]
