# Generated by Django 5.1.6 on 2025-03-29 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0027_polvosparticula'),
        ('otras_fuentes', '0015_nombrevertedero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polvosparticula',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.oace'),
        ),
    ]
