# Generated by Django 5.1.6 on 2025-03-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0029_ruido'),
    ]

    operations = [
        migrations.AddField(
            model_name='polvosparticula',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='ruido',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
