# Generated by Django 5.1.6 on 2025-04-21 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0030_polvosparticula_year_ruido_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desechospeligroso',
            old_name='priorizado',
            new_name='declaracion_jurada',
        ),
        migrations.AddField(
            model_name='desechospeligroso',
            name='licencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='desechospeligroso',
            name='osde',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='desechospeligroso',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], default=3),
        ),
        migrations.AlterField(
            model_name='polvosparticula',
            name='emisiones_co',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='polvosparticula',
            name='emisiones_covdm',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='polvosparticula',
            name='emisiones_no2',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='polvosparticula',
            name='emisiones_pm10',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='polvosparticula',
            name='emisiones_pm25',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='polvosparticula',
            name='emisiones_so2',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
