# Generated by Django 5.1.6 on 2025-04-21 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0031_rename_priorizado_desechospeligroso_declaracion_jurada_and_more'),
        ('otras_fuentes', '0016_actividadprincipal_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desechospeligroso',
            name='desecho_generado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.desechogenerado'),
        ),
    ]
