# Generated by Django 5.1.6 on 2025-04-21 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0032_alter_desechospeligroso_desecho_generado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desechospeligroso',
            name='osde',
        ),
    ]
