# Generated by Django 5.1.6 on 2025-04-21 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0033_remove_desechospeligroso_osde'),
        ('otras_fuentes', '0016_actividadprincipal_entidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desechospeligroso',
            name='subordinacion',
        ),
        migrations.AddField(
            model_name='desechospeligroso',
            name='osde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.osde'),
        ),
    ]
