# Generated by Django 5.1.6 on 2025-04-23 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0034_remove_desechospeligroso_subordinacion_and_more'),
        ('otras_fuentes', '0017_entidaddp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desechospeligroso',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.entidaddp'),
        ),
    ]
