# Generated by Django 5.1.6 on 2025-04-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0036_atmosferaparametro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desechospeligroso',
            name='cuenca_hidrografica',
        ),
    ]
