# Generated by Django 5.1.6 on 2025-04-26 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0037_remove_desechospeligroso_cuenca_hidrografica'),
        ('otras_fuentes', '0017_entidaddp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquido',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.categoria'),
        ),
        migrations.AlterField(
            model_name='liquido',
            name='cuenca_hidrografica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.cuencahidrografica'),
        ),
        migrations.AlterField(
            model_name='liquido',
            name='cuerpo_agua_afectado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.cuerpoaguaafectado'),
        ),
        migrations.AlterField(
            model_name='liquido',
            name='cuerpo_receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.cuerporeceptor'),
        ),
        migrations.AlterField(
            model_name='liquido',
            name='nombre_fc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.nombrefuentecontaminante'),
        ),
        migrations.AlterField(
            model_name='liquido',
            name='organos_gobierno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.organos_gobierno'),
        ),
        migrations.AlterField(
            model_name='liquido',
            name='osde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.osde'),
        ),
        migrations.AlterField(
            model_name='liquido',
            name='otras_instituciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.otras_instituciones'),
        ),
        migrations.AlterField(
            model_name='liquido',
            name='prioridad_fc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.prioridad_fc'),
        ),
        migrations.AlterField(
            model_name='liquido',
            name='sistema_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.sistematratamiento'),
        ),
        migrations.AlterField(
            model_name='liquido',
            name='tipo_residual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.tiporesidual'),
        ),
        migrations.AlterField(
            model_name='liquido',
            name='uso_principal_afectado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.usoprincipalafectado'),
        ),
    ]
