# Generated by Django 5.1.6 on 2025-04-26 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0038_alter_liquido_categoria_and_more'),
        ('otras_fuentes', '0017_entidaddp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquido',
            name='nombre_fc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otras_fuentes.nombrefuentecontaminante'),
        ),
    ]
