# Generated by Django 5.1.6 on 2025-04-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0039_alter_liquido_nombre_fc'),
        ('otras_fuentes', '0018_alter_nombrefuentecontaminante_municipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desechospeligroso',
            name='desecho_generado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.desechogenerado'),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='osde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.osde'),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='practica_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practica_1', to='otras_fuentes.practica'),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='practica_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practica_2', to='otras_fuentes.practica'),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='practica_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practica_3', to='otras_fuentes.practica'),
        ),
        migrations.AlterField(
            model_name='desechospeligroso',
            name='practica_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practica_4', to='otras_fuentes.practica'),
        ),
    ]
