# Generated by Django 5.1.6 on 2025-04-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0040_alter_desechospeligroso_desecho_generado_and_more'),
        ('otras_fuentes', '0018_alter_nombrefuentecontaminante_municipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polvosparticula',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.municipio'),
        ),
        migrations.AlterField(
            model_name='polvosparticula',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.oace'),
        ),
        migrations.AlterField(
            model_name='ruido',
            name='actividad_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.actividadprincipal'),
        ),
        migrations.AlterField(
            model_name='ruido',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.municipio'),
        ),
        migrations.AlterField(
            model_name='ruido',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otras_fuentes.oace'),
        ),
    ]
