# Generated by Django 5.1.6 on 2025-05-15 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contaminantes', '0041_alter_polvosparticula_municipio_and_more'),
        ('otras_fuentes', '0018_alter_nombrefuentecontaminante_municipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquido',
            name='nombre_fc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquido', to='otras_fuentes.nombrefuentecontaminante'),
        ),
    ]
